name: business-profile-env
channels: 
  - default

dependencies:
  - python=3.8
  - pip
  - pip:
    - pandas
    - notebook
    - snowflake-connector-python
    - snowflake-connector-python[pandas]
    - snowflake-snowpark-python